### ISSUE TITLE
[Enhancement]: Set Model Parameters for Title Run

### ISSUE THREAD

**Issue by dvejsada** [LibreChat-AI/LibreChat#7557]
### What features would you like to see added?

Currently, the region for title model is always similar as for the model in main conversation. This however creates issues, as in some regions, some models may not be available or may be used only via cross-region inference, which requires a region-specific identifier.

For example, the latest Anthropic Claude 4  Sonnet in only available within EU in eu-south-2 region, but **no other small model is available here** (e.g. haiku 3) to be then used as title model, so the title fetching fails.

It would be thus great if you could set a **specific region for title model, independently on what region is used for main conversation/agent model** (I understand these are separate API call anyway).

### More details

The updated config may look like this:

```yaml
endpoints:
  bedrock:
    titleModel: 
      modelName: "anthropic.claude-3-haiku-20240307-v1:0"
      modelRegion: "eu-central-1"
    streamRate: 35
    availableRegions:
      - "us-east-1"
      - "us-west-2"
```

### Which components are impacted by your request?

General

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
